### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by SDBowen** [kitspace/kitspace-using-gitea#5]
I got the Docker containers going easily with the readme instructions.

I did initially get the error below, due to not cloning the Gitea sub repository. Maybe mentioning that in the install process would be nice. 
```
Building gitea
ERROR: Cannot locate specified Dockerfile: Dockerfile
```
After completing the install and registering an account, I get this from `http://kitspace.test:3000/`

![Screenshot from 2019-12-22 21-04-11](https://user-images.githubusercontent.com/22715037/71326699-d0b46d80-24fe-11ea-9726-107802b2912e.png)

**Comment by kasbah** [comment]
Ah, right. Nuke your own clone (`rm -rf gitea`). You need the [hacked version](https://github.com/kitspace/gitea/tree/kitspace-rebased) which you can get by running:

```
git submodule update --init
```

That needs to be added to the instructions.

**Comment by SDBowen** [comment]
Yup, that did it.

![Screenshot from 2019-12-22 21-31-03](https://user-images.githubusercontent.com/22715037/71326967-6dc4d580-2502-11ea-808f-8e3654dbba64.png)
